production:
  BIBLESEARCH_API_KEY: <%= ENV['BIBLESEARCH_API_KEY'] %>

development:
  BIBLESEARCH_API_KEY: jwCOaN1d5j4WtlWECf8thPMqKJg4uA8TwBiMPaqK

test:
  BIBLESEARCH_API_KEY: jwCOaN1d5j4WtlWECf8thPMqKJg4uA8TwBiMPaqK